config/routes.rb
Tienda::Application.routes.draw do
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get 'contacto' => 'store#contacto'
  get 'preguntas' => 'store#faq'
  get 'novedades' => 'store#news'
  get 'conozcanos' => 'store#about_us'

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :store, only: :index do
    collection do
      match '/:product_type', to: 'store#index', via: :get
    end
  end
  resources :orders, only: [:show, :new, :create]
  resources :line_items
  resources :carts, except: [:new, :edit, :index]

  # todo: este deberia irse
  resources :estadordens
  get 'nuevoEstado' => 'estadordens#nuevo'

  resources :products, only: :show

  root to: 'store#promotions', as: 'promociones'

  namespace :admin do
    resources :orders, only: [:index, :show, :destroy]
    resources :payment_methods, except: :show
    resources :posts
    resources :product_types
    resources :products do
      resources :prices, only: [:index, :new, :create]
    end
    resources :promotions do
      resources :promotion_lines, as: :lines, except: [:index, :show]
      member do
        put :publish
        put :unpublish
      end
    end
    resources :users
  end
end

app/views/shared/_admin_menu.haml
.colorFullMenu.left
  %ul.unstyled
    %li.header.border.red= link_to t('.promotions'), admin_promotions_path, class: current_section([admin_promotions_path])
    %li.header.border.orange= link_to t('.orders'), admin_orders_path, class: current_section([admin_orders_path])
    %li.sublist
      %ul.unstyled
        - Estadorden::STATUSES.each_with_index do |state, i|
          %li.border{ class: RAINBOW_COLORS[i%RAINBOW_COLORS.size] }= link_to state.pluralize, admin_orders_path( filter: { state: state} ), class: ( current_subsection( [admin_orders_path] ) if @state == state )
    %li.header.border.yellow= link_to t('.catalog'), admin_products_path, class: current_section(admin_products_urls)
    %li.header.border.green= link_to 'Tipos de productos', admin_product_types_path, class: current_section([admin_product_types_path])
    %li.header.border.lightBlue= link_to t('.paytypes'), admin_payment_methods_path, class: current_section([admin_payment_methods_path])
    %li.header.border.cyan= link_to t('.users'), admin_users_path, class: current_section([admin_users_path])
    %li.header.border.blue= link_to t('.news'),admin_posts_path, class: current_section([admin_posts_path])

    -#todo: current_section para subsecciones

app/views/shared/_footer.haml
%footer.footer
  .row-fluid
    .span3
      = link_to t('.news'), novedades_path
    .span3
      = link_to t('.faq'), preguntas_path
    .span3
      = link_to t('.contact'), contacto_path
    .span3
      = link_to t('.about_us'), conozcanos_path

app/views/shared/_locale_selector.haml
#locale_selector.btn-group.pull-right.hide
  %a{href: '#', class: 'btn btn-primary dropdown-toggle', data: { toggle: 'dropdown' }}
    Idioma
    %span.caret
  %ul.dropdown-menu
    %li
      %a{href: '../en' } Ingles
    %li
      %a{href: '../es' } Español

app/views/shared/_login.haml
.login
  .login-buttons
    - if session[:user_id]
      = link_to t('.exit'), logout_path, method: :delete, class: 'btn btn-danger btn-small stitched'
    - else
      = link_to t('.login'), login_path, class: 'btn btn-info btn-small stitched'

app/views/shared/_search.haml
.search
  = form_tag store_index_path , method: :get, html: { class: 'form-search' } do |f|
    = text_field_tag :search, params[:search], placeholder: 'Coloque el nombre del producto a buscar', class: 'search-query'
    = submit_tag 'Buscar', name: nil, class: 'btn btn-small btn-inverse stitched', disable_with: 'Buscando...'

app/views/shared/_store_menu.haml
.colorFullMenu.left
  %ul.unstyled
    %li.header.border.red= link_to t('.offers'), promociones_path, class: current_section( ['/', promociones_path] )
    %li.header.border.orange= link_to t('.products'), store_index_path(product_type: @product_types.first.name), class: current_section( product_urls )
    %li.sublist
      = render partial: 'store/store_submenu'
    %li.header.border.yellow= link_to t('.cart'), @cart, class: current_section( cart_urls )

app/views/shared/_title.haml
.section-title
  %div.image.left
  %h3= @title
  %div.image.right

app/views/shared/_user_menu.haml
- if session[:user_id]
  %ul.nav.nav-list
    %li= link_to 'Mis compras', ''
    %li= link_to 'Favoritos', ''
    %li= link_to 'Carrito', ''