config/routes.rb
Tienda::Application.routes.draw do
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get 'contacto' => 'store#contacto'
  get 'preguntas' => 'store#faq'
  get 'novedades' => 'store#news'
  get 'conozcanos' => 'store#about_us'

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :store, only: :index do
    collection do
      match '/:product_type', to: 'store#index', via: :get
    end
  end
  resources :orders, only: [:show, :new, :create]
  resources :line_items
  resources :carts, except: [:new, :edit, :index]

  # todo: este deberia irse
  resources :estadordens
  get 'nuevoEstado' => 'estadordens#nuevo'

  resources :products, only: :show

  root to: 'store#promotions', as: 'promociones'

  namespace :admin do
    resources :orders, only: [:index, :show, :destroy]
    resources :payment_methods, except: :show
    resources :posts
    resources :product_types
    resources :products do
      resources :prices, only: [:index, :new, :create]
    end
    resources :promotions do
      resources :promotion_lines, as: :lines, except: [:index, :show]
      member do
        put :publish
        put :unpublish
      end
    end
    resources :users
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  
  def add_product(item)
    current_item = nil
    case item
      when Product
        current_item = line_items.where(product_id: item.id).first
        if current_item
          current_item.quantity += 1
        else
          current_item = line_items.build(product_id: item.id)
        end
      else
        current_item = line_items.where(promotion_id: item.id).first
        if current_item
          current_item.quantity += 1
        else
          current_item = line_items.build(promotion_id: item.id)
        end
    end
    current_item
  end
  
  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
  
  def total_items
    line_items.sum(:quantity)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, only: [:create, :update, :destroy, :show]


  # GET /carts/1
  # GET /carts/1.xml
  def show
    @title = I18n.t('carts.cart.title')
    set_page_meta_tags @title, nil
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, :notice=>'Invalid Cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @cart }
      end
    end
  end

  # POST /carts
  # POST /carts.xml
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to(@cart, :notice => 'Cart was successfully created.') }
        format.xml  { render :xml => @cart, :status => :created, :location => @cart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.xml
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to(@cart, :notice => 'Cart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.xml
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id]=nil

    respond_to do |format|
      format.html { redirect_to(store_index_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/carts/_cart.html.erb
<div id="carrito">
  <div class="span6">
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>Cantidad</th>
        <th>Detalle</th>
        <th>Subtotal</th>
      </tr>
      </thead>
      <tbody>
        <%= render @cart.line_items %>
      </tbody>
    </table>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="span6">
      <h2 class="pull-right">
        <%= t('.total') %>
        <span class="cart-total"><%= number_to_currency(cart.total_price) %></span>
      </h2>
    </div>
    <div class="span3">
      <%= link_to t('.buy'), new_order_path, class: 'btn btn-primary btn-large stitched margin-5', remote: true, data: { target: 'modal', modal: true } %>
      <%= link_to t('.emptycart'), cart, method: :delete, confirm: t('.confirm'), class: 'btn btn-danger btn-small stitched margin-5' %>
    </div>
  </div>
  </div>
</div>

app/views/carts/_floating_cart.haml
.floating-cart{ data: { element: 'floating-cart' } }
  .cart
    %h3 Su carrito
    %table.table
      %tbody#line_items_table_body
        = render partial: 'line_items/floating_line_item', collection: cart.line_items if cart
      %tr
        %td Total:
        %td
          %b
            $
            %span{ data: { type: 'cart-total' } }= cart.total_price.to_f if cart
        %td
    = link_to t('carts.cart.buy'), new_order_path, class: 'btn btn-primary btn-large stitched', remote: true, data: { target: 'modal', modal: true }
    = link_to t('carts.cart.emptycart'), cart, method: :delete, confirm: t('carts.cart.confirm'), class: 'btn btn-danger btn-small stitched'
  .cart-tab{ data: { action: 'toggle-cart', toggle: 'tooltip' }, title: 'Abrir el carrito' }
    .icon.icon-shopping-cart.big-icon

app/views/carts/show.html.erb
<% unless @cart.line_items.empty? %>
  <%= render @cart %>
<% else %>
  <h3>No tienes productos en el carrito todavia.</h3>
<% end %>