config/routes.rb
Tienda::Application.routes.draw do
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get 'contacto' => 'store#contacto'
  get 'preguntas' => 'store#faq'
  get 'novedades' => 'store#news'
  get 'conozcanos' => 'store#about_us'

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :store, only: :index do
    collection do
      match '/:product_type', to: 'store#index', via: :get
    end
  end
  resources :orders, only: [:show, :new, :create]
  resources :line_items
  resources :carts, except: [:new, :edit, :index]

  # todo: este deberia irse
  resources :estadordens
  get 'nuevoEstado' => 'estadordens#nuevo'

  resources :products, only: :show

  root to: 'store#promotions', as: 'promociones'

  namespace :admin do
    resources :orders, only: [:index, :show, :destroy]
    resources :payment_methods, except: :show
    resources :posts
    resources :product_types
    resources :products do
      resources :prices, only: [:index, :new, :create]
    end
    resources :promotions do
      resources :promotion_lines, as: :lines, except: [:index, :show]
      member do
        put :publish
        put :unpublish
      end
    end
    resources :users
  end
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base

  AVAILABLE_COLORS = [['Amarillo', 'yellow'], ['Azul', 'blue'], ['Negro', 'black'] , ['Rojo', 'red'], ['Verde', 'green']]

  before_destroy :ensure_not_referenced_by_any_line_item

  has_many :promotion_lines, dependent: :destroy
  has_many :line_items

  accepts_nested_attributes_for :promotion_lines, allow_destroy: true

  attr_accessible :color_combo, :end_date, :start_date, :title, :total, :promotion_lines, :description

  validates :title, :color_combo, presence: true

  scope :published, -> { where(state: 'published') }

  def to_s
    title
  end

  #states
  def publish
    self.state = 'published'
    self.save
  end

  def unpublish
    self.state = 'not-published'
    self.save
  end

  def published?
    state == 'published'
  end

  #pricing
  def total_cost
    promotion_lines.sum(&:cost)
  end

  def total_price
    promotion_lines.sum(&:total)
  end

  private
  def ensure_not_referenced_by_any_line_item
    if line_items.any?
      errors.add(:base, I18n.t('admin.promotions.errors.referenced_by_line_item'))
      false
    end
  end
end

app/controllers/admin/promotions_controller.rb
class Admin::PromotionsController < Admin::AdminController
  before_filter :get_product, except: :index

  # GET /promotions
  # GET /promotions.json
  def index
    @title = t('admin.promotions.index.title')
    @promotions = ( @product ? @product.promotions : Promotion.all )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promotions }
    end
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
    @promotion = Promotion.includes(:promotion_lines).find(params[:id])
    @promotion_lines = @promotion.promotion_lines
    @title = "Promocion: #{@promotion.title}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promotion }
    end
  end

  # GET /promotions/new
  # GET /promotions/new.json
  def new
    @title = t('admin.promotions.new.title')
    @promotion = Promotion.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promotion }
    end
  end

  # GET /promotions/1/edit
  def edit
    @title = t('admin.promotions.edit.title')
    @promotion = Promotion.find(params[:id])
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @title = t('admin.promotions.new.title')
    @promotion = Promotion.new params[:promotion]
    @promotion.state = 'not-published'
    respond_to do |format|
      if @promotion.save
        format.html { redirect_to ['admin', @promotion], notice: 'Promotion was successfully created.' }
        format.json { render json: @promotion, status: :created, location: @promotion }
      else
        format.html { render action: 'new' }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promotions/1
  # PUT /promotions/1.json
  def update
    @title = t('admin.promotions.edit.title')
    @promotion = Promotion.find(params[:id])
    params[:promotion][:state] = 'not-published'

    respond_to do |format|
      if @promotion.update_attributes(params[:promotion])
        format.html { redirect_to ['admin', @promotion], notice: 'Promotion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion = Promotion.find(params[:id])

    if @promotion.destroy
      js_notify message: t('admin.promotions.destroy.success'), type: 'alert-error', time: 2500
      render nothing: true, content_type: 'text/html'
    else
      message = "#{t('admin.promotions.destroy.error')}: #{@promotion.errors[:base].first}"
      js_notify message: message, type: 'alert-info', time: 2500
      render nothing: true
    end
  end

  def preview
    render partial: 'preview', content_type: 'text/html'
  end

  def publish
    @promotion = Promotion.find(params[:id])
    @promotion.publish
    js_notify message: 'Promocion visible al publico'
    render partial: 'state', content_type: 'text/html'
  end

  def unpublish
    @promotion = Promotion.find(params[:id])
    @promotion.unpublish
    js_notify message: 'Promocion oculta al publico'
    render partial: 'state', content_type: 'text/html'
  end

  private
  def get_product
    @product = Product.find(params[:product_id]) if params[:product_id]
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_filter :get_product, except: :index

  # GET /promotions
  # GET /promotions.json
  def index
    @title = 'Listado de Promociones'
    @promotions = ( @product ? @product.promotions : Promotion.all )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promotions }
    end
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
    @promotion = Promotion.includes(:promotion_lines).find(params[:id])
    @promotion_lines = @promotion.promotion_lines
    @title = "Promocion: #{@promotion.title}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promotion }
    end
  end

  # GET /promotions/new
  # GET /promotions/new.json
  def new
    @title = 'Nueva promocion'
    @promotion = Promotion.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promotion }
    end
  end

  # GET /promotions/1/edit
  def edit
    @title = 'Editando la promocion'
    @promotion = Promotion.find(params[:id])
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @title = 'Nueva promocion'
    @promotion = Promotion.new params[:promotion]
    @promotion.state = 'not-published'
    respond_to do |format|
      if @promotion.save
        format.html { redirect_to @promotion, notice: 'Promotion was successfully created.' }
        format.json { render json: @promotion, status: :created, location: @promotion }
      else
        format.html { render action: "new" }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promotions/1
  # PUT /promotions/1.json
  def update
    @title = 'Editando la promocion'
    @promotion = Promotion.find(params[:id])
    params[:promotion][:state] = 'not-published'

    respond_to do |format|
      if @promotion.update_attributes(params[:promotion])
        format.html { redirect_to @promotion, notice: 'Promotion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion = Promotion.find(params[:id])
    @promotion.destroy

    respond_to do |format|
      format.html { redirect_to promotions_url }
      format.json { head :no_content }
    end
  end

  def preview
    render partial: 'preview', content_type: 'text/html'
  end

  def publish
    @promotion = Promotion.find(params[:id])
    @promotion.publish
    js_notify message: 'Promocion visible al publico'
    render partial: 'state', content_type: 'text/html'
  end

  def unpublish
    @promotion = Promotion.find(params[:id])
    @promotion.unpublish
    js_notify message: 'Promocion oculta al publico'
    render partial: 'state', content_type: 'text/html'
  end

  private
  def get_product
    @product = Product.find(params[:product_id]) if params[:product_id]
  end
end

app/views/admin/promotions/_form.html.haml
= f.error_notification

= f.input :title, input_html: { class: 'span8' }
.row-fluid
  .span3
    = f.input :start_date, as: :string, input_html: { class: 'datepicker', value: (@start_date ? @start_date.strftime('%d/%m/%Y') : Date.today.strftime('%d/%m/%Y')) }
  .span3
    = f.input :end_date, as: :string, input_html: { class: 'datepicker', value: (@end_date ? @end_date.strftime('%d/%m/%Y') : (Date.today + 1.months).strftime('%d/%m/%Y'))}
  .span2
    = f.input :color_combo, collection: Promotion::AVAILABLE_COLORS
= f.input :description, input_html: { rows: 5, class: 'span8' }

app/views/admin/promotions/_promotion.haml
%tr{ id: dom_id(promotion) }
  %td= promotion.title
  %td= promotion.start_date.strftime('%d/%m/%Y')
  %td= promotion.end_date.strftime('%d/%m/%Y')
  %td= promotion.color_combo
  %td= promotion.state
  %td= promotion.total
  %td
    = link_to_show ['admin', promotion]
    = link_to_edit edit_admin_promotion_path(promotion)
    = srbuj_link_to_destroy ['admin', promotion], data: { confirm: t('admin.promotions.destroy.confirm'), target: dom_id(promotion) }

app/views/admin/promotions/_state.haml
#state
  .label= t("admin.promotions.show.#{@promotion.state}")
  - if @promotion.published?
    = link_to t('admin.promotions.show.unpublish'), ['unpublish', 'admin', @promotion], class: 'btn btn-warning stitched', method: :put, remote: true, data: { target: 'state', replace: true }
  - else
    = link_to t('admin.promotions.show.publish'), ['publish', 'admin', @promotion], class: 'btn btn-success stitched', method: :put, remote: true, data: { target: 'state', replace: true }

app/views/admin/promotions/edit.html.haml
= simple_form_for ['admin',@promotion] do |f|
  = render partial: 'form', locals: { f: f }

  = f.button :submit, t('admin.promotions.edit.submit'), class: 'btn btn-primary stitched btn-large side-margin'
  = link_to_back admin_promotions_path

app/views/admin/promotions/index.html.haml
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th= Promotion.human_attribute_name :title
      %th= Promotion.human_attribute_name :start_date
      %th= Promotion.human_attribute_name :end_date
      %th= Promotion.human_attribute_name :color_combo
      %th= Promotion.human_attribute_name :state
      %th= Promotion.human_attribute_name :total
      %th
  %tbody
    = render @promotions

= link_to_new t('admin.promotions.index.new'), new_admin_promotion_path

app/views/admin/promotions/new.html.haml
= simple_form_for ['admin',@promotion] do |f|
  = render partial: 'form', locals: { f: f }

  = f.button :submit, t('admin.promotions.new.submit'), class: 'btn btn-primary stitched btn-large side-margin'
  = link_to_back admin_promotions_path

app/views/admin/promotions/show.html.haml
.span3
  = link_to_edit edit_admin_promotion_path(@promotion)
  %p
    %b= Promotion.human_attribute_name :description
    = @promotion.description
  %p
    %b= Promotion.human_attribute_name :color_combo
    = @promotion.color_combo
  %p
    %b= Promotion.human_attribute_name :start_date
    = @promotion.start_date.strftime('%d/%m/%Y')
  %p
    %b= Promotion.human_attribute_name :end_date
    = @promotion.end_date.strftime('%d/%m/%Y')
  = render partial: 'state'

  %h2
    %b= Promotion.human_attribute_name :total
    %span{ data: { promotion_total: true } }= number_to_currency @promotion.total
.span8
  %h3= t('admin.promotions.show.subtitle')
  #promotion_lines
    = render partial: 'admin/promotion_lines/promotion_line', collection: @promotion_lines
  = srbuj_link_to_new t('admin.promotions.show.add_product'), new_admin_promotion_line_path(@promotion), title: t('admin.promotions.show.add_product_tooltip')
.clearfix
= link_to_back admin_promotions_path