config/routes.rb
Tienda::Application.routes.draw do
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get 'contacto' => 'store#contacto'
  get 'preguntas' => 'store#faq'
  get 'novedades' => 'store#news'
  get 'conozcanos' => 'store#about_us'

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :store, only: :index do
    collection do
      match '/:product_type', to: 'store#index', via: :get
    end
  end
  resources :orders, only: [:show, :new, :create]
  resources :line_items
  resources :carts, except: [:new, :edit, :index]

  # todo: este deberia irse
  resources :estadordens
  get 'nuevoEstado' => 'estadordens#nuevo'

  resources :products, only: :show

  root to: 'store#promotions', as: 'promociones'

  namespace :admin do
    resources :orders, only: [:index, :show, :destroy]
    resources :payment_methods, except: :show
    resources :posts
    resources :product_types
    resources :products do
      resources :prices, only: [:index, :new, :create]
    end
    resources :promotions do
      resources :promotion_lines, as: :lines, except: [:index, :show]
      member do
        put :publish
        put :unpublish
      end
    end
    resources :users
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  belongs_to :promotion

  def total_price
    if product_id
      product.actual_public_price * quantity
    else
      promotion.total * quantity
    end
  end

  def total_costo
    cost = ( product_id ? product.actual_cost : promotion.total_cost )
    cost * quantity
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_filter :authorize,:only=>[:create, :destroy]

  # GET /line_items
  # GET /line_items.xml
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.xml
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.xml
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.xml
  def create
    @cart = current_cart
    new_item = Product.find(params[:product_id]) if params[:product_id]
    new_item = Promotion.find(params[:promotion_id]) if params[:promotion_id]
    @line_item = @cart.add_product(new_item)

    #todo: que responda con js tambien y que actualice el carrito
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to :back }
        format.js { render partial: 'line_items/floating_line_item',
                           locals: { floating_line_item: @line_item },
                           content_type: 'text/html' }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.xml
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to(@line_item, :notice => 'Line item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @line_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.xml
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to(store_index_path) }
      format.js #preguntar como hacer para que el carrito suba cuando lo elimino y que no sea de golpe.
      format.xml  { head :ok }
    end
  end
end

app/views/line_items/_floating_line_item.haml
-#todo: mejorar esto
- if floating_line_item.product
  %tr{id: "line_#{dom_id(floating_line_item.product)}"}
    %td= "#{floating_line_item.quantity} x #{floating_line_item.product}"
    %td
      $
      %span{ data: { type: 'price' } }= floating_line_item.total_price
    %td= link_to_destroy line_item_path(floating_line_item), confirm: t('line_items.index.confirm'), class: 'red'
- else
  %tr{id: "line_#{dom_id(floating_line_item.promotion)}"}
    %td= "#{floating_line_item.quantity} x #{floating_line_item.promotion}"
    %td
      $
      %span{ data: { type: 'price' } }= floating_line_item.total_price
    %td= link_to_destroy line_item_path(floating_line_item), confirm: t('line_items.index.confirm'), class: 'red'

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> <%= t('.error') %></h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= raw msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit t('.submit') %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
  <td>
    <%= link_to_destroy line_item_path(line_item), confirm: t('.confirm'), class: 'red' unless params[:controller] == 'orders' %>
    <span class="pull-right"><%= line_item.quantity %></span>
  </td>
  <% if line_item.product %>
    <td><%= truncate(strip_tags(line_item.product.to_s), length: 40) %></td>
<% else %>
    <td><%= truncate(strip_tags(line_item.promotion.title), length: 40) %></td>
  <% end %>
  <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1><%= t('.title') %></h1>

<table>
  <tr>
    <th><%= t('.product') %></th>
    <th><%= t('.cart') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to t('.show'), line_item %></td>
    <td><%= link_to t('.edit'), edit_line_item_path(line_item) %></td>
    <td><%= link_to t('.destroy'), line_item, :confirm => t('.confirm'), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('.newline'), new_line_item_path %>

app/views/line_items/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), line_items_path %>

app/views/line_items/show.html.erb
<%if notice.present?  %>
<p id="notice"><%= notice %></p>
<% end %>
<p>
  <b><%= t('.product') %></b>
  <%= @line_item.product_id %>
</p>

<p>
  <b><%= t('.cart') %></b>
  <%= @line_item.cart_id %>
</p>


<%= link_to t('.edit'), edit_line_item_path(@line_item) %> |
<%= link_to t('.back'), line_items_path %>